# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(386, 452)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(3, 10, 381, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nextFrame_button = QtGui.QPushButton(self.groupBox)
        self.nextFrame_button.setGeometry(QtCore.QRect(280, 30, 86, 25))
        self.nextFrame_button.setObjectName(_fromUtf8("nextFrame_button"))
        self.prevFrame_button = QtGui.QPushButton(self.groupBox)
        self.prevFrame_button.setGeometry(QtCore.QRect(10, 30, 86, 25))
        self.prevFrame_button.setObjectName(_fromUtf8("prevFrame_button"))
        self.playPause_button = QtGui.QPushButton(self.groupBox)
        self.playPause_button.setGeometry(QtCore.QRect(100, 30, 86, 25))
        self.playPause_button.setObjectName(_fromUtf8("playPause_button"))
        self.stop_button = QtGui.QPushButton(self.groupBox)
        self.stop_button.setGeometry(QtCore.QRect(190, 30, 86, 25))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.animationMovement_horizontalSlider = QtGui.QSlider(self.groupBox)
        self.animationMovement_horizontalSlider.setGeometry(QtCore.QRect(10, 60, 361, 29))
        self.animationMovement_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationMovement_horizontalSlider.setObjectName(_fromUtf8("animationMovement_horizontalSlider"))
        self.averaging_spinBox = QtGui.QSpinBox(self.groupBox)
        self.averaging_spinBox.setGeometry(QtCore.QRect(320, 90, 55, 22))
        self.averaging_spinBox.setMinimum(1)
        self.averaging_spinBox.setMaximum(50)
        self.averaging_spinBox.setObjectName(_fromUtf8("averaging_spinBox"))
        self.average_label = QtGui.QLabel(self.groupBox)
        self.average_label.setGeometry(QtCore.QRect(253, 93, 62, 15))
        self.average_label.setObjectName(_fromUtf8("average_label"))
        self.frameNumber_label = QtGui.QLabel(self.groupBox)
        self.frameNumber_label.setGeometry(QtCore.QRect(10, 90, 62, 15))
        self.frameNumber_label.setObjectName(_fromUtf8("frameNumber_label"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(3, 210, 381, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.directory_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.directory_lineEdit.setGeometry(QtCore.QRect(90, 30, 281, 27))
        self.directory_lineEdit.setObjectName(_fromUtf8("directory_lineEdit"))
        self.directory_label = QtGui.QLabel(self.groupBox_2)
        self.directory_label.setGeometry(QtCore.QRect(10, 35, 68, 17))
        self.directory_label.setObjectName(_fromUtf8("directory_label"))
        self.number_of_files_label = QtGui.QLabel(self.groupBox_2)
        self.number_of_files_label.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.number_of_files_label.setObjectName(_fromUtf8("number_of_files_label"))
        self.number_of_files_value_label = QtGui.QLabel(self.groupBox_2)
        self.number_of_files_value_label.setGeometry(QtCore.QRect(130, 90, 68, 17))
        self.number_of_files_value_label.setObjectName(_fromUtf8("number_of_files_value_label"))
        self.format_label = QtGui.QLabel(self.groupBox_2)
        self.format_label.setGeometry(QtCore.QRect(10, 110, 101, 17))
        self.format_label.setObjectName(_fromUtf8("format_label"))
        self.format_value_label = QtGui.QLabel(self.groupBox_2)
        self.format_value_label.setGeometry(QtCore.QRect(130, 110, 68, 17))
        self.format_value_label.setObjectName(_fromUtf8("format_value_label"))
        self.header_file_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.header_file_lineEdit.setGeometry(QtCore.QRect(90, 55, 281, 27))
        self.header_file_lineEdit.setObjectName(_fromUtf8("header_file_lineEdit"))
        self.directory_label_2 = QtGui.QLabel(self.groupBox_2)
        self.directory_label_2.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.directory_label_2.setObjectName(_fromUtf8("directory_label_2"))
        self.binaryFiles_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.binaryFiles_checkBox.setGeometry(QtCore.QRect(260, 90, 121, 22))
        self.binaryFiles_checkBox.setObjectName(_fromUtf8("binaryFiles_checkBox"))
        self.loadingFiles_progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.loadingFiles_progressBar.setGeometry(QtCore.QRect(10, 150, 371, 23))
        self.loadingFiles_progressBar.setProperty("value", 0)
        self.loadingFiles_progressBar.setObjectName(_fromUtf8("loadingFiles_progressBar"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 130, 101, 17))
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuColors = QtGui.QMenu(self.menubar)
        self.menuColors.setObjectName(_fromUtf8("menuColors"))
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        self.menuGraph = QtGui.QMenu(self.menubar)
        self.menuGraph.setObjectName(_fromUtf8("menuGraph"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_File = QtGui.QAction(MainWindow)
        self.actionSave_File.setObjectName(_fromUtf8("actionSave_File"))
        self.action_omf_file = QtGui.QAction(MainWindow)
        self.action_omf_file.setObjectName(_fromUtf8("action_omf_file"))
        self.action_ohf_file = QtGui.QAction(MainWindow)
        self.action_ohf_file.setObjectName(_fromUtf8("action_ohf_file"))
        self.actionLoad_File = QtGui.QAction(MainWindow)
        self.actionLoad_File.setObjectName(_fromUtf8("actionLoad_File"))
        self.actionLoad_Data = QtGui.QAction(MainWindow)
        self.actionLoad_Data.setObjectName(_fromUtf8("actionLoad_Data"))
        self.actionShow_3D_Model = QtGui.QAction(MainWindow)
        self.actionShow_3D_Model.setObjectName(_fromUtf8("actionShow_3D_Model"))
        self.actionShow_Range_Plot = QtGui.QAction(MainWindow)
        self.actionShow_Range_Plot.setObjectName(_fromUtf8("actionShow_Range_Plot"))
        self.actionShow_2D_layer_Plot = QtGui.QAction(MainWindow)
        self.actionShow_2D_layer_Plot.setObjectName(_fromUtf8("actionShow_2D_layer_Plot"))
        self.actionLoad_Header_File = QtGui.QAction(MainWindow)
        self.actionLoad_Header_File.setObjectName(_fromUtf8("actionLoad_Header_File"))
        self.menuFile.addAction(self.actionSave_File)
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Header_File)
        self.menuSimulation.addAction(self.actionShow_3D_Model)
        self.menuGraph.addAction(self.actionShow_Range_Plot)
        self.menuGraph.addAction(self.actionShow_2D_layer_Plot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuColors.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation", None))
        self.nextFrame_button.setText(_translate("MainWindow", ">>", None))
        self.prevFrame_button.setText(_translate("MainWindow", "<<", None))
        self.playPause_button.setText(_translate("MainWindow", "Play", None))
        self.stop_button.setText(_translate("MainWindow", "Stop", None))
        self.average_label.setText(_translate("MainWindow", "Average:", None))
        self.frameNumber_label.setText(_translate("MainWindow", "0", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chosen Directory", None))
        self.directory_label.setText(_translate("MainWindow", "Directory", None))
        self.number_of_files_label.setText(_translate("MainWindow", "Number of files", None))
        self.number_of_files_value_label.setText(_translate("MainWindow", "0", None))
        self.format_label.setText(_translate("MainWindow", "File format", None))
        self.format_value_label.setText(_translate("MainWindow", ".", None))
        self.directory_label_2.setText(_translate("MainWindow", "Header File", None))
        self.binaryFiles_checkBox.setText(_translate("MainWindow", "Binary Files", None))
        self.label.setText(_translate("MainWindow", "Loading Files:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuColors.setTitle(_translate("MainWindow", "Colors", None))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation", None))
        self.menuGraph.setTitle(_translate("MainWindow", "Plot", None))
        self.actionSave_File.setText(_translate("MainWindow", "Save File", None))
        self.action_omf_file.setText(_translate("MainWindow", ".omf file", None))
        self.action_ohf_file.setText(_translate("MainWindow", ".ohf file", None))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File", None))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Directory", None))
        self.actionShow_3D_Model.setText(_translate("MainWindow", "Show 3D Model", None))
        self.actionShow_Range_Plot.setText(_translate("MainWindow", "Show Range Plot", None))
        self.actionShow_2D_layer_Plot.setText(_translate("MainWindow", "Show 2D layer Plot", None))
        self.actionLoad_Header_File.setText(_translate("MainWindow", "Load Header File", None))

